call plug#begin()
Plug 'valloric/youcompleteme'
"крутая строка состояния
Plug 'vim-airline/vim-airline'
"автозакрытие кавычек и скобок
Plug 'jiangmiao/auto-pairs'
"удобное комментирование кода
Plug 'tomtom/tcomment_vim'
"для редактирования нескольких курсоров
Plug 'terryma/vim-multiple-cursors'
"отображение скопированного блока
Plug 'machakann/vim-highlightedyank'
"цветовая схема
Plug 'morhetz/gruvbox'
"быстрое перемещение строк вверх/вниз
Plug 'matze/vim-move'
"поиск файла по содержимому
Plug 'rking/ag.vim'
"быстрое перемещение по коду
Plug 'easymotion/vim-easymotion'
"выделение измененных строк в git
Plug 'airblade/vim-gitgutter'
"подсвечивает пробелы в начале/конце строк
Plug 'ntpeters/vim-better-whitespace'
"удаляет лишние пробелы
Plug 'thirtythreeforty/lessspace.vim'
call plug#end()

let g:move_key_modifier = 'C'
let g:ycm_global_ycm_extra_conf = '~/.vim/.ycm_extra_conf.py'
let g:ycm_key_list_stop_completion = ['<C-y>', '<CR>']
let mapleader = ","
"убрать подсветку после поиска шаблона
nnoremap <silent> <leader>c :nohlsearch<CR>
nnoremap <F4> :NERDTreeToggle<CR>
nmap <F8> :TagbarToggle<CR>
" , + s
map <Leader> <Plug>(easymotion-prefix)
"создание вкладки
imap <F5> <Esc>:browse tabnew<CR>
map <F5> <Esc>:browse tabnew<CR>

"включить подсветку синтаксиса
syntax on
colorscheme gruvbox
set background=dark
"показывать номера строк
set number
"показывать относительные номера строк
" set relativenumber
"табы вместо пробелов
set noexpandtab
"размер табуляции по умолчанию
set tabstop=4
"подсвечивать поиск
set hlsearch
"поиск по мере набора.
set incsearch
"игнорировать регистр при поиске
set ignorecase
"подсвечивать текущую линию, где курсор
set cursorline
"поддержка мыши
" set mouse=a
"set mousemodel=popup
"добавить линию на 120 символах
set colorcolumn=120
"кодировка текста по умолчанию utf8
set termencoding=utf8
set termguicolors
set langmap=!\\"№\\;%?*ёйцукенгшщзхъфывапролджэячсмитьбюЁЙЦУКЕHГШЩЗХЪФЫВАПРОЛДЖЭЯЧСМИТЬБЮ;!@#$%&*`qwertyuiop[]asdfghjkl\\;'zxcvbnm\\,.~QWERTYUIOP{}ASDFGHJKL:\\"ZXCVBNM<>

"перемещение табом по автокомплиту
inoremap <expr><tab> pumvisible() ? "\<c-n>" : "\<tab>"
"автозакрытие окна-подсказки автокомплита
autocmd InsertLeave,CompleteDone * if pumvisible() == 0 | pclose | endif
