version: '3.3'

services:
  transmission:
    image: linuxserver/transmission
    container_name: transmission
    restart: always
    volumes:
      - /data/shared/video:/downloads
      - /home/sergey/Загрузки:/watch
    # - path to data:/config
    environment:
      PUID: "1000"
      PGID: "1000"
      # USER: "user"
      # PASS: "1"
    ports:
      - 9091:9091
      - 51413:51413
      - 51413:51413/udp
